import 'package:ai_tray/theme/theme_palette.dart';
import 'package:flutter/material.dart';

/// Branded color theme presets for AI Tray.
///
/// Each preset exposes intentional [light] and [dark] [ThemePalette]s. Theme
/// mode selects which palette is active; FlexColorScheme fills remaining M3
/// roles from the brand seeds while surfaces come from the palette.
enum ThemePreset {
  cursor,
  tokyoNight,
  catppuccinMocha,
  nord,
  oneDark,
  dracula,
  github,
  gruvbox,
}

/// Metadata and full light/dark palettes for a [ThemePreset].
extension ThemePresetX on ThemePreset {
  /// Stable storage key.
  String get storageValue => name;

  /// Default preset when none is stored.
  static const ThemePreset defaultPreset = ThemePreset.cursor;

  static ThemePreset fromStorage(String? value) {
    if (value == null || value.isEmpty) return defaultPreset;
    return ThemePreset.values.firstWhere(
      (p) => p.name == value,
      orElse: () => defaultPreset,
    );
  }

  String get displayName => switch (this) {
    ThemePreset.cursor => 'Cursor',
    ThemePreset.tokyoNight => 'Tokyo Night',
    ThemePreset.catppuccinMocha => 'Catppuccin Mocha',
    ThemePreset.nord => 'Nord',
    ThemePreset.oneDark => 'One Dark',
    ThemePreset.dracula => 'Dracula',
    ThemePreset.github => 'GitHub',
    ThemePreset.gruvbox => 'Gruvbox',
  };

  String get description => switch (this) {
    ThemePreset.cursor => 'Modern developer-tool surfaces.',
    ThemePreset.tokyoNight => 'Cool blue night / day palettes.',
    ThemePreset.catppuccinMocha => 'Soft pastel mocha / latte tones.',
    ThemePreset.nord => 'Arctic Nord polar night and snow storm.',
    ThemePreset.oneDark => 'Atom One Dark / One Light.',
    ThemePreset.dracula => 'Classic Dracula purple accents.',
    ThemePreset.github => 'GitHub light and dark chrome.',
    ThemePreset.gruvbox => 'Earthy Gruvbox warm oranges.',
  };

  /// Swatch used in collapsed pickers (dark primary).
  Color get previewColor => dark.primary;

  ThemePalette paletteFor(Brightness brightness) {
    return brightness == Brightness.dark ? dark : light;
  }

  /// Light-mode surfaces and accents.
  ThemePalette get light => switch (this) {
    ThemePreset.cursor => const ThemePalette(
      primary: Color(0xFF5B5FC7),
      secondary: Color(0xFF0969DA),
      tertiary: Color(0xFF8250DF),
      error: Color(0xFFCF222E),
      background: Color(0xFFF6F8FA),
      surface: Color(0xFFFFFFFF),
      surfaceAlt: Color(0xFFEFF2F5),
      border: Color(0xFFD0D7DE),
      textPrimary: Color(0xFF1F2328),
      textSecondary: Color(0xFF656D76),
      textMuted: Color(0xFF8B949E),
      success: Color(0xFF1A7F37),
      warning: Color(0xFF9A6700),
      highUsage: Color(0xFFBC4C00),
      info: Color(0xFF0969DA),
      cyanAccent: Color(0xFF0550AE),
      onAccent: Color(0xFFFFFFFF),
      focus: Color(0xFF5B5FC7),
      buttonDisabled: Color(0xFFD0D7DE),
      meterTrack: Color(0xFFEFF2F5),
    ),
    ThemePreset.tokyoNight => const ThemePalette(
      primary: Color(0xFF2E7DE9),
      secondary: Color(0xFF9854F1),
      tertiary: Color(0xFF07879D),
      error: Color(0xFFF52A65),
      background: Color(0xFFE1E2E7),
      surface: Color(0xFFD5D6DB),
      surfaceAlt: Color(0xFFC4C8DA),
      border: Color(0xFFA8AECB),
      textPrimary: Color(0xFF3760BF),
      textSecondary: Color(0xFF6172B0),
      textMuted: Color(0xFF848CB5),
      success: Color(0xFF587539),
      warning: Color(0xFF8C6C3E),
      highUsage: Color(0xFFB15C00),
      info: Color(0xFF2E7DE9),
      cyanAccent: Color(0xFF007197),
      onAccent: Color(0xFFFFFFFF),
      focus: Color(0xFF2E7DE9),
      buttonDisabled: Color(0xFFA8AECB),
      meterTrack: Color(0xFFC4C8DA),
    ),
    ThemePreset.catppuccinMocha => const ThemePalette(
      primary: Color(0xFF8839EF),
      secondary: Color(0xFF1E66F5),
      tertiary: Color(0xFFEA76CB),
      error: Color(0xFFD20F39),
      background: Color(0xFFEFF1F5),
      surface: Color(0xFFE6E9EF),
      surfaceAlt: Color(0xFFDCE0E8),
      border: Color(0xFFCCD0DA),
      textPrimary: Color(0xFF4C4F69),
      textSecondary: Color(0xFF6C6F85),
      textMuted: Color(0xFF9CA0B0),
      success: Color(0xFF40A02B),
      warning: Color(0xFFDF8E1D),
      highUsage: Color(0xFFFE640B),
      info: Color(0xFF1E66F5),
      cyanAccent: Color(0xFF04A5E5),
      onAccent: Color(0xFFFFFFFF),
      focus: Color(0xFF8839EF),
      buttonDisabled: Color(0xFFCCD0DA),
      meterTrack: Color(0xFFDCE0E8),
    ),
    ThemePreset.nord => const ThemePalette(
      primary: Color(0xFF5E81AC),
      secondary: Color(0xFF81A1C1),
      tertiary: Color(0xFF88C0D0),
      error: Color(0xFFBF616A),
      background: Color(0xFFECEFF4),
      surface: Color(0xFFE5E9F0),
      surfaceAlt: Color(0xFFD8DEE9),
      border: Color(0xFFC7CEDA),
      textPrimary: Color(0xFF2E3440),
      textSecondary: Color(0xFF4C566A),
      textMuted: Color(0xFF6B7589),
      success: Color(0xFFA3BE8C),
      warning: Color(0xFFEBCB8B),
      highUsage: Color(0xFFD08770),
      info: Color(0xFF5E81AC),
      cyanAccent: Color(0xFF88C0D0),
      onAccent: Color(0xFFECEFF4),
      focus: Color(0xFF5E81AC),
      buttonDisabled: Color(0xFFC7CEDA),
      meterTrack: Color(0xFFD8DEE9),
    ),
    ThemePreset.oneDark => const ThemePalette(
      primary: Color(0xFF4078F2),
      secondary: Color(0xFF0184BC),
      tertiary: Color(0xFFA626A4),
      error: Color(0xFFE45649),
      background: Color(0xFFFAFAFA),
      surface: Color(0xFFFFFFFF),
      surfaceAlt: Color(0xFFF0F0F0),
      border: Color(0xFFE5E5E6),
      textPrimary: Color(0xFF383A42),
      textSecondary: Color(0xFF696C77),
      textMuted: Color(0xFFA0A1A7),
      success: Color(0xFF50A14F),
      warning: Color(0xFFC18401),
      highUsage: Color(0xFF986801),
      info: Color(0xFF4078F2),
      cyanAccent: Color(0xFF0184BC),
      onAccent: Color(0xFFFFFFFF),
      focus: Color(0xFF4078F2),
      buttonDisabled: Color(0xFFE5E5E6),
      meterTrack: Color(0xFFF0F0F0),
    ),
    ThemePreset.dracula => const ThemePalette(
      primary: Color(0xFF7C3AED),
      secondary: Color(0xFFDB61A2),
      tertiary: Color(0xFF2A9D8F),
      error: Color(0xFFFF5555),
      background: Color(0xFFF8F8F2),
      surface: Color(0xFFFFFFFF),
      surfaceAlt: Color(0xFFEDEDED),
      border: Color(0xFFD6D6D0),
      textPrimary: Color(0xFF282A36),
      textSecondary: Color(0xFF44475A),
      textMuted: Color(0xFF6272A4),
      success: Color(0xFF2A9D8F),
      warning: Color(0xFFFFB86C),
      highUsage: Color(0xFFFF79C6),
      info: Color(0xFF8BE9FD),
      cyanAccent: Color(0xFF8BE9FD),
      onAccent: Color(0xFFFFFFFF),
      focus: Color(0xFF7C3AED),
      buttonDisabled: Color(0xFFD6D6D0),
      meterTrack: Color(0xFFEDEDED),
    ),
    ThemePreset.github => const ThemePalette(
      primary: Color(0xFF0969DA),
      secondary: Color(0xFF1A7F37),
      tertiary: Color(0xFF8250DF),
      error: Color(0xFFCF222E),
      background: Color(0xFFFFFFFF),
      surface: Color(0xFFF6F8FA),
      surfaceAlt: Color(0xFFEFF2F5),
      border: Color(0xFFD0D7DE),
      textPrimary: Color(0xFF1F2328),
      textSecondary: Color(0xFF656D76),
      textMuted: Color(0xFF8B949E),
      success: Color(0xFF1A7F37),
      warning: Color(0xFF9A6700),
      highUsage: Color(0xFFBC4C00),
      info: Color(0xFF0969DA),
      cyanAccent: Color(0xFF0550AE),
      onAccent: Color(0xFFFFFFFF),
      focus: Color(0xFF0969DA),
      buttonDisabled: Color(0xFFD0D7DE),
      meterTrack: Color(0xFFEFF2F5),
    ),
    ThemePreset.gruvbox => const ThemePalette(
      primary: Color(0xFFAF3A03),
      secondary: Color(0xFF79740E),
      tertiary: Color(0xFF076678),
      error: Color(0xFF9D0006),
      background: Color(0xFFFBF1C7),
      surface: Color(0xFFF2E5BC),
      surfaceAlt: Color(0xFFEBDBB2),
      border: Color(0xFFD5C4A1),
      textPrimary: Color(0xFF3C3836),
      textSecondary: Color(0xFF504945),
      textMuted: Color(0xFF7C6F64),
      success: Color(0xFF79740E),
      warning: Color(0xFFB57614),
      highUsage: Color(0xFFAF3A03),
      info: Color(0xFF076678),
      cyanAccent: Color(0xFF427B58),
      onAccent: Color(0xFFFBF1C7),
      focus: Color(0xFFAF3A03),
      buttonDisabled: Color(0xFFD5C4A1),
      meterTrack: Color(0xFFEBDBB2),
    ),
  };

  /// Dark-mode surfaces and accents.
  ThemePalette get dark => switch (this) {
    ThemePreset.cursor => const ThemePalette(
      primary: Color(0xFF8B8CF0),
      secondary: Color(0xFF58A6FF),
      tertiary: Color(0xFFA371F7),
      error: Color(0xFFF85149),
      background: Color(0xFF0D1117),
      surface: Color(0xFF161B22),
      surfaceAlt: Color(0xFF21262D),
      border: Color(0xFF30363D),
      textPrimary: Color(0xFFE6EDF3),
      textSecondary: Color(0xFF8B949E),
      textMuted: Color(0xFF6E7681),
      success: Color(0xFF22C55E),
      warning: Color(0xFFEAB308),
      highUsage: Color(0xFFF97316),
      info: Color(0xFF3B82F6),
      cyanAccent: Color(0xFF06B6D4),
      onAccent: Color(0xFF0D1117),
      focus: Color(0xFF8B8CF0),
      buttonDisabled: Color(0xFF30363D),
      meterTrack: Color(0xFF21262D),
    ),
    ThemePreset.tokyoNight => const ThemePalette(
      primary: Color(0xFF7AA2F7),
      secondary: Color(0xFFBB9AF7),
      tertiary: Color(0xFF7DCFFF),
      error: Color(0xFFF7768E),
      background: Color(0xFF1A1B26),
      surface: Color(0xFF24283B),
      surfaceAlt: Color(0xFF292E42),
      border: Color(0xFF3B4261),
      textPrimary: Color(0xFFC0CAF5),
      textSecondary: Color(0xFFA9B1D6),
      textMuted: Color(0xFF565F89),
      success: Color(0xFF9ECE6A),
      warning: Color(0xFFE0AF68),
      highUsage: Color(0xFFFF9E64),
      info: Color(0xFF7AA2F7),
      cyanAccent: Color(0xFF7DCFFF),
      onAccent: Color(0xFF1A1B26),
      focus: Color(0xFF7AA2F7),
      buttonDisabled: Color(0xFF3B4261),
      meterTrack: Color(0xFF292E42),
    ),
    ThemePreset.catppuccinMocha => const ThemePalette(
      primary: Color(0xFFCBA6F7),
      secondary: Color(0xFF89B4FA),
      tertiary: Color(0xFFF5C2E7),
      error: Color(0xFFF38BA8),
      background: Color(0xFF1E1E2E),
      surface: Color(0xFF181825),
      surfaceAlt: Color(0xFF313244),
      border: Color(0xFF45475A),
      textPrimary: Color(0xFFCDD6F4),
      textSecondary: Color(0xFFA6ADC8),
      textMuted: Color(0xFF6C7086),
      success: Color(0xFFA6E3A1),
      warning: Color(0xFFF9E2AF),
      highUsage: Color(0xFFFAB387),
      info: Color(0xFF89B4FA),
      cyanAccent: Color(0xFF94E2D5),
      onAccent: Color(0xFF1E1E2E),
      focus: Color(0xFFCBA6F7),
      buttonDisabled: Color(0xFF45475A),
      meterTrack: Color(0xFF313244),
    ),
    ThemePreset.nord => const ThemePalette(
      primary: Color(0xFF88C0D0),
      secondary: Color(0xFF81A1C1),
      tertiary: Color(0xFFB48EAD),
      error: Color(0xFFBF616A),
      background: Color(0xFF2E3440),
      surface: Color(0xFF3B4252),
      surfaceAlt: Color(0xFF434C5E),
      border: Color(0xFF4C566A),
      textPrimary: Color(0xFFECEFF4),
      textSecondary: Color(0xFFD8DEE9),
      textMuted: Color(0xFFA0A8B8),
      success: Color(0xFFA3BE8C),
      warning: Color(0xFFEBCB8B),
      highUsage: Color(0xFFD08770),
      info: Color(0xFF81A1C1),
      cyanAccent: Color(0xFF8FBCBB),
      onAccent: Color(0xFF2E3440),
      focus: Color(0xFF88C0D0),
      buttonDisabled: Color(0xFF4C566A),
      meterTrack: Color(0xFF434C5E),
    ),
    ThemePreset.oneDark => const ThemePalette(
      primary: Color(0xFF61AFEF),
      secondary: Color(0xFF56B6C2),
      tertiary: Color(0xFFC678DD),
      error: Color(0xFFE06C75),
      background: Color(0xFF282C34),
      surface: Color(0xFF21252B),
      surfaceAlt: Color(0xFF2C313A),
      border: Color(0xFF3E4451),
      textPrimary: Color(0xFFABB2BF),
      textSecondary: Color(0xFF9DA5B4),
      textMuted: Color(0xFF5C6370),
      success: Color(0xFF98C379),
      warning: Color(0xFFE5C07B),
      highUsage: Color(0xFFD19A66),
      info: Color(0xFF61AFEF),
      cyanAccent: Color(0xFF56B6C2),
      onAccent: Color(0xFF282C34),
      focus: Color(0xFF61AFEF),
      buttonDisabled: Color(0xFF3E4451),
      meterTrack: Color(0xFF2C313A),
    ),
    ThemePreset.dracula => const ThemePalette(
      primary: Color(0xFFBD93F9),
      secondary: Color(0xFFFF79C6),
      tertiary: Color(0xFF50FA7B),
      error: Color(0xFFFF5555),
      background: Color(0xFF282A36),
      surface: Color(0xFF21222C),
      surfaceAlt: Color(0xFF44475A),
      border: Color(0xFF6272A4),
      textPrimary: Color(0xFFF8F8F2),
      textSecondary: Color(0xFFBD93F9),
      textMuted: Color(0xFF6272A4),
      success: Color(0xFF50FA7B),
      warning: Color(0xFFFFB86C),
      highUsage: Color(0xFFFF79C6),
      info: Color(0xFF8BE9FD),
      cyanAccent: Color(0xFF8BE9FD),
      onAccent: Color(0xFF282A36),
      focus: Color(0xFFBD93F9),
      buttonDisabled: Color(0xFF44475A),
      meterTrack: Color(0xFF44475A),
    ),
    ThemePreset.github => const ThemePalette(
      primary: Color(0xFF58A6FF),
      secondary: Color(0xFF3FB950),
      tertiary: Color(0xFFA371F7),
      error: Color(0xFFF85149),
      background: Color(0xFF0D1117),
      surface: Color(0xFF161B22),
      surfaceAlt: Color(0xFF21262D),
      border: Color(0xFF30363D),
      textPrimary: Color(0xFFE6EDF3),
      textSecondary: Color(0xFF8B949E),
      textMuted: Color(0xFF6E7681),
      success: Color(0xFF3FB950),
      warning: Color(0xFFD29922),
      highUsage: Color(0xFFDB6D28),
      info: Color(0xFF58A6FF),
      cyanAccent: Color(0xFF39C5CF),
      onAccent: Color(0xFF0D1117),
      focus: Color(0xFF58A6FF),
      buttonDisabled: Color(0xFF30363D),
      meterTrack: Color(0xFF21262D),
    ),
    ThemePreset.gruvbox => const ThemePalette(
      primary: Color(0xFFFE8019),
      secondary: Color(0xFFB8BB26),
      tertiary: Color(0xFF83A598),
      error: Color(0xFFFB4934),
      background: Color(0xFF282828),
      surface: Color(0xFF3C3836),
      surfaceAlt: Color(0xFF504945),
      border: Color(0xFF665C54),
      textPrimary: Color(0xFFEBDBB2),
      textSecondary: Color(0xFFD5C4A1),
      textMuted: Color(0xFFA89984),
      success: Color(0xFFB8BB26),
      warning: Color(0xFFFABD2F),
      highUsage: Color(0xFFFE8019),
      info: Color(0xFF83A598),
      cyanAccent: Color(0xFF8EC07C),
      onAccent: Color(0xFF282828),
      focus: Color(0xFFFE8019),
      buttonDisabled: Color(0xFF665C54),
      meterTrack: Color(0xFF504945),
    ),
  };
}
